version: '3.1'
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: url_shortner_redis
  app:
    build:
      context: .. # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "80:80"
    environment:
      - REDIS_URL=redis:6379
      - HOSTNAME_DNS=localhost
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: url_shortner_backend

networks:
  backend: